/**
 * App market
 * App market
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@peraMIC.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Device
 */
export class Device {
    /**
     * Path
     */
    path?: string;
    system?: string;
    version?: string;
    kernel?: string;
    autoCheckUpdates: boolean;
    autoInstallUpdates: boolean;
}
