/**
 * App market
 * App market
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@menucha.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Mount
 */
export interface Mount {
    /**
     * Mount type
     */
    type?: string;
    /**
     * Mount source
     */
    source?: string;
    /**
     * Mount destination
     */
    destination?: string;
    /**
     * Mount options
     */
    options?: string;
}
